org: swayam73
app: sk-rest-api-app
service: sk-rest-api-app

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
